FROM node:20 AS build
WORKDIR /app
COPY iqra-frontend/package*.json ./
RUN npm install
COPY iqra-frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
